export interface Review {
  id: number;
  author: string;
  rating: number;
  date: string;
  comment: string;
  avatar: string;
}

export const reviewsData: Record<number, Review[]> = {
  1: [
    {
      id: 1,
      author: "Mariana S.",
      rating: 5,
      date: "28/02/2026",
      comment:
        "O melhor ovo de colher que já provei! Os dois sabores são espetaculares e o chocolate é premium.",
      avatar: "M",
    },
    {
      id: 2,
      author: "Carlos A.",
      rating: 5,
      date: "25/02/2026",
      comment:
        "Produto excelente! A qualidade da Cacau Show nunca decepciona. Minha família inteira adorou.",
      avatar: "C",
    },
    {
      id: 3,
      author: "Juliana P.",
      rating: 4.5,
      date: "22/02/2026",
      comment:
        "Muito gostoso, achei o tamanho perfeito. Embalagem linda também!",
      avatar: "J",
    },
    {
      id: 4,
      author: "Roberto M.",
      rating: 5,
      date: "20/02/2026",
      comment:
        "Comprei para presentear e foi um sucesso. O recheio é cremoso e derrete na boca.",
      avatar: "R",
    },
    {
      id: 5,
      author: "Ana Clara",
      rating: 5,
      date: "18/02/2026",
      comment: "Simplesmente perfeito! Vale cada centavo, o sabor é incrível.",
      avatar: "A",
    },
    {
      id: 6,
      author: "Felipe T.",
      rating: 4.5,
      date: "15/02/2026",
      comment: "Chocolate de altíssima qualidade. Recomendo!",
      avatar: "F",
    },
    {
      id: 7,
      author: "Beatriz L.",
      rating: 5,
      date: "12/02/2026",
      comment:
        "Embalagem premium e sabor incrível. Superou todas as expectativas.",
      avatar: "B",
    },
  ],
  2: [
    {
      id: 1,
      author: "Lucas R.",
      rating: 5,
      date: "27/02/2026",
      comment:
        "Meu filho amou! A embalagem do Scooby-Doo é incrível e o chocolate é delicioso.",
      avatar: "L",
    },
    {
      id: 2,
      author: "Patrícia F.",
      rating: 5,
      date: "24/02/2026",
      comment: "Produto lindo e saboroso. Perfeito para presentear criançada!",
      avatar: "P",
    },
    {
      id: 3,
      author: "Daniel S.",
      rating: 4.5,
      date: "21/02/2026",
      comment:
        "Ótima qualidade, meus sobrinhos adoraram. Chocolate muito gostoso.",
      avatar: "D",
    },
    {
      id: 4,
      author: "Camila N.",
      rating: 5,
      date: "19/02/2026",
      comment: "Chegou rápido e muito bem embalado. Recomendo demais!",
      avatar: "C",
    },
    {
      id: 5,
      author: "Rodrigo B.",
      rating: 5,
      date: "16/02/2026",
      comment:
        "As crianças ficaram encantadas com o Scooby! Qualidade excelente.",
      avatar: "R",
    },
    {
      id: 6,
      author: "Fernanda K.",
      rating: 4.5,
      date: "14/02/2026",
      comment: "Muito fofo e gostoso! Valeu muito a pena.",
      avatar: "F",
    },
  ],
  3: [
    {
      id: 1,
      author: "Amanda L.",
      rating: 5,
      date: "26/02/2026",
      comment: "A pelúcia com LED é um diferencial incrível! Minha filha amou.",
      avatar: "A",
    },
    {
      id: 2,
      author: "Thiago M.",
      rating: 5,
      date: "23/02/2026",
      comment:
        "Produto de qualidade superior. A pelúcia é muito fofa e bem feita.",
      avatar: "T",
    },
    {
      id: 3,
      author: "Gabriela S.",
      rating: 4.5,
      date: "20/02/2026",
      comment: "Chocolate delicioso e a pelúcia é linda! Adorei.",
      avatar: "G",
    },
    {
      id: 4,
      author: "Eduardo P.",
      rating: 5,
      date: "18/02/2026",
      comment: "Perfeito! O LED funciona muito bem e o chocolate é excelente.",
      avatar: "E",
    },
    {
      id: 5,
      author: "Bianca R.",
      rating: 5,
      date: "15/02/2026",
      comment:
        "Minha sobrinha ficou apaixonada pelo Zangadinho. Recomendo muito!",
      avatar: "B",
    },
    {
      id: 6,
      author: "Rafael O.",
      rating: 4.5,
      date: "13/02/2026",
      comment: "Achei muito criativo! Qualidade top da Cacau Show.",
      avatar: "R",
    },
    {
      id: 7,
      author: "Larissa C.",
      rating: 5,
      date: "11/02/2026",
      comment: "Entrega rápida, produto maravilhoso. Super recomendo!",
      avatar: "L",
    },
    {
      id: 8,
      author: "Marcos V.",
      rating: 5,
      date: "08/02/2026",
      comment: "Adorei! A pelúcia ficará de recordação aqui em casa.",
      avatar: "M",
    },
  ],
  4: [
    {
      id: 1,
      author: "Vanessa T.",
      rating: 5,
      date: "25/02/2026",
      comment:
        "Os Chocomonstros são demais! Meu filho adora bolhas de sabão e chocolate.",
      avatar: "V",
    },
    {
      id: 2,
      author: "Gustavo H.",
      rating: 4.5,
      date: "22/02/2026",
      comment: "Muito criativo e divertido. Qualidade excelente como sempre.",
      avatar: "G",
    },
    {
      id: 3,
      author: "Priscila A.",
      rating: 5,
      date: "19/02/2026",
      comment:
        "Produto incrível! As crianças se divertem muito com as bolhinhas.",
      avatar: "P",
    },
    {
      id: 4,
      author: "Bruno L.",
      rating: 5,
      date: "17/02/2026",
      comment:
        "Achei genial! Chocolate delicioso e o brinquedo entretém bastante.",
      avatar: "B",
    },
    {
      id: 5,
      author: "Tatiana S.",
      rating: 4.5,
      date: "14/02/2026",
      comment: "Minha filha adorou! Chegou rápido e bem embalado.",
      avatar: "T",
    },
    {
      id: 6,
      author: "Anderson F.",
      rating: 5,
      date: "12/02/2026",
      comment: "Excelente custo benefício! Produto de qualidade.",
      avatar: "A",
    },
  ],
  5: [
    {
      id: 1,
      author: "João P.",
      rating: 5,
      date: "24/02/2026",
      comment:
        "Edição especial maravilhosa! Para quem ama futebol e chocolate, é perfeito.",
      avatar: "J",
    },
    {
      id: 2,
      author: "Carla M.",
      rating: 5,
      date: "21/02/2026",
      comment: "Comprei para meu marido e ele amou! A bola temática é linda.",
      avatar: "C",
    },
    {
      id: 3,
      author: "Ricardo N.",
      rating: 4.5,
      date: "18/02/2026",
      comment: "Produto diferenciado e de excelente qualidade. Recomendo!",
      avatar: "R",
    },
    {
      id: 4,
      author: "Silvia O.",
      rating: 5,
      date: "16/02/2026",
      comment: "Adorei a embalagem da CBF! Chocolate delicioso.",
      avatar: "S",
    },
    {
      id: 5,
      author: "Marcelo K.",
      rating: 5,
      date: "13/02/2026",
      comment: "Perfeito para colecionadores! Qualidade impecável.",
      avatar: "M",
    },
    {
      id: 6,
      author: "Renata B.",
      rating: 4.5,
      date: "11/02/2026",
      comment: "Meu filho ficou encantado com a bola. Vale muito a pena!",
      avatar: "R",
    },
    {
      id: 7,
      author: "Paulo S.",
      rating: 5,
      date: "09/02/2026",
      comment: "Chocolate excelente e a bola é de ótima qualidade também.",
      avatar: "P",
    },
    {
      id: 8,
      author: "Aline F.",
      rating: 5,
      date: "07/02/2026",
      comment: "Presenteei meu irmão e foi um sucesso total!",
      avatar: "A",
    },
    {
      id: 9,
      author: "Victor R.",
      rating: 4.5,
      date: "05/02/2026",
      comment: "Edição especial muito bacana. Recomendo para fãs de futebol!",
      avatar: "V",
    },
  ],
  6: [
    {
      id: 1,
      author: "Helena C.",
      rating: 5,
      date: "23/02/2026",
      comment: "Snoopy oficial é tudo! Minha filha não larga a pelúcia.",
      avatar: "H",
    },
    {
      id: 2,
      author: "Fábio A.",
      rating: 5,
      date: "20/02/2026",
      comment:
        "Produto maravilhoso! A pelúcia é muito bem feita e o chocolate delicioso.",
      avatar: "F",
    },
    {
      id: 3,
      author: "Cristina L.",
      rating: 4.5,
      date: "17/02/2026",
      comment: "Adorei! O Snoopy é fofo demais e o chocolate é excelente.",
      avatar: "C",
    },
    {
      id: 4,
      author: "Leandro M.",
      rating: 5,
      date: "15/02/2026",
      comment: "Comprei para minha esposa e ela amou! Qualidade top.",
      avatar: "L",
    },
    {
      id: 5,
      author: "Isabela T.",
      rating: 5,
      date: "12/02/2026",
      comment: "Perfeito! A pelúcia oficial faz toda a diferença.",
      avatar: "I",
    },
    {
      id: 6,
      author: "Diego S.",
      rating: 4.5,
      date: "10/02/2026",
      comment: "Muito bom! Embalagem linda e chocolate delicioso.",
      avatar: "D",
    },
    {
      id: 7,
      author: "Natália P.",
      rating: 5,
      date: "08/02/2026",
      comment: "Encantador! O Snoopy é uma fofura e vale muito a pena.",
      avatar: "N",
    },
  ],
  7: [
    {
      id: 1,
      author: "Sofia R.",
      rating: 5,
      date: "22/02/2026",
      comment:
        "Minha filha ama Florzinha! O ovo ficou lindo e o chocolate delicioso.",
      avatar: "S",
    },
    {
      id: 2,
      author: "Murilo B.",
      rating: 5,
      date: "19/02/2026",
      comment:
        "Produto incrível! As Meninas Superpoderosas fazem sucesso sempre.",
      avatar: "M",
    },
    {
      id: 3,
      author: "Elaine K.",
      rating: 4.5,
      date: "16/02/2026",
      comment: "Muito fofo! Qualidade excelente como sempre.",
      avatar: "E",
    },
    {
      id: 4,
      author: "William G.",
      rating: 5,
      date: "14/02/2026",
      comment: "Perfeito! Minha sobrinha adorou a Florzinha.",
      avatar: "W",
    },
    {
      id: 5,
      author: "Luciana F.",
      rating: 5,
      date: "11/02/2026",
      comment: "Chocolate gostoso e embalagem linda! Super recomendo.",
      avatar: "L",
    },
    {
      id: 6,
      author: "Alexandre N.",
      rating: 4.5,
      date: "09/02/2026",
      comment: "Ótima opção para presentear! Qualidade impecável.",
      avatar: "A",
    },
    {
      id: 7,
      author: "Raquel S.",
      rating: 5,
      date: "07/02/2026",
      comment: "Adorei! As meninas vão amar essa Páscoa.",
      avatar: "R",
    },
    {
      id: 8,
      author: "Henrique L.",
      rating: 5,
      date: "05/02/2026",
      comment: "Produto de qualidade! Florzinha está perfeita.",
      avatar: "H",
    },
  ],
  8: [
    {
      id: 1,
      author: "Melissa A.",
      rating: 5,
      date: "21/02/2026",
      comment:
        "Lindinha é a favorita! Produto maravilhoso e chocolate delicioso.",
      avatar: "M",
    },
    {
      id: 2,
      author: "Gabriel P.",
      rating: 4.5,
      date: "18/02/2026",
      comment: "Muito bom! Embalagem bonita e chocolate de qualidade.",
      avatar: "G",
    },
    {
      id: 3,
      author: "Andressa M.",
      rating: 5,
      date: "15/02/2026",
      comment: "Perfeito! Minha filha ficou apaixonada pela Lindinha.",
      avatar: "A",
    },
    {
      id: 4,
      author: "Vitor S.",
      rating: 5,
      date: "13/02/2026",
      comment: "Excelente produto! Qualidade da Cacau Show sempre surpreende.",
      avatar: "V",
    },
    {
      id: 5,
      author: "Daniela F.",
      rating: 4.5,
      date: "10/02/2026",
      comment: "Adorei! Chegou rápido e muito bem embalado.",
      avatar: "D",
    },
    {
      id: 6,
      author: "Roberto C.",
      rating: 5,
      date: "08/02/2026",
      comment: "Produto de excelente qualidade! Recomendo muito.",
      avatar: "R",
    },
    {
      id: 7,
      author: "Jéssica L.",
      rating: 5,
      date: "06/02/2026",
      comment: "Simplesmente perfeito! As meninas vão amar.",
      avatar: "J",
    },
    {
      id: 8,
      author: "Fernando R.",
      rating: 4.5,
      date: "04/02/2026",
      comment: "Muito bom! Valeu a pena comprar.",
      avatar: "F",
    },
    {
      id: 9,
      author: "Bruna T.",
      rating: 5,
      date: "02/02/2026",
      comment: "Maravilhoso! Chocolate delicioso e embalagem linda.",
      avatar: "B",
    },
  ],
  9: [
    {
      id: 1,
      author: "Samantha K.",
      rating: 5,
      date: "20/02/2026",
      comment: "Docinho é a melhor! Produto incrível e chocolate delicioso.",
      avatar: "S",
    },
    {
      id: 2,
      author: "Márcio B.",
      rating: 5,
      date: "17/02/2026",
      comment: "Qualidade excepcional! Minha filha amou.",
      avatar: "M",
    },
    {
      id: 3,
      author: "Renata G.",
      rating: 4.5,
      date: "14/02/2026",
      comment: "Muito fofo e gostoso! Valeu muito a pena.",
      avatar: "R",
    },
    {
      id: 4,
      author: "Igor S.",
      rating: 5,
      date: "12/02/2026",
      comment: "Perfeito! Embalagem linda e chocolate excelente.",
      avatar: "I",
    },
    {
      id: 5,
      author: "Carolina M.",
      rating: 5,
      date: "09/02/2026",
      comment: "Adorei! Produto de alta qualidade.",
      avatar: "C",
    },
    {
      id: 6,
      author: "Wesley F.",
      rating: 4.5,
      date: "07/02/2026",
      comment: "Ótima compra! As crianças adoraram.",
      avatar: "W",
    },
    {
      id: 7,
      author: "Lívia P.",
      rating: 5,
      date: "05/02/2026",
      comment: "Maravilhoso! Super recomendo.",
      avatar: "L",
    },
    {
      id: 8,
      author: "André N.",
      rating: 5,
      date: "03/02/2026",
      comment: "Produto excelente! Qualidade impecável.",
      avatar: "A",
    },
    {
      id: 9,
      author: "Thaís R.",
      rating: 4.5,
      date: "01/02/2026",
      comment: "Muito bom! Docinho é demais.",
      avatar: "T",
    },
    {
      id: 10,
      author: "Leonardo C.",
      rating: 5,
      date: "30/01/2026",
      comment: "Perfeito para presentear! Recomendo.",
      avatar: "L",
    },
  ],
  10: [
    {
      id: 1,
      author: "Cláudia S.",
      rating: 5,
      date: "19/02/2026",
      comment: "Clássico que nunca decepciona! Os bombons são deliciosos.",
      avatar: "C",
    },
    {
      id: 2,
      author: "Sérgio M.",
      rating: 4.5,
      date: "16/02/2026",
      comment: "Excelente qualidade! Sempre compro da Cacau Show.",
      avatar: "S",
    },
    {
      id: 3,
      author: "Adriana L.",
      rating: 5,
      date: "13/02/2026",
      comment: "Adorei os bombons sortidos! Cada um melhor que o outro.",
      avatar: "A",
    },
    {
      id: 4,
      author: "José F.",
      rating: 5,
      date: "11/02/2026",
      comment: "Produto de primeira! Qualidade excepcional.",
      avatar: "J",
    },
    {
      id: 5,
      author: "Simone P.",
      rating: 4.5,
      date: "08/02/2026",
      comment: "Muito gostoso! Valeu a pena comprar.",
      avatar: "S",
    },
    {
      id: 6,
      author: "Matheus R.",
      rating: 5,
      date: "06/02/2026",
      comment: "Perfeito! Chocolate ao leite cremoso e bombons deliciosos.",
      avatar: "M",
    },
    {
      id: 7,
      author: "Vera K.",
      rating: 5,
      date: "04/02/2026",
      comment: "Excelente! Super recomendo para Páscoa.",
      avatar: "V",
    },
    {
      id: 8,
      author: "Antônio B.",
      rating: 4.5,
      date: "02/02/2026",
      comment: "Ótimo produto! Qualidade top.",
      avatar: "A",
    },
    {
      id: 9,
      author: "Lúcia G.",
      rating: 5,
      date: "31/01/2026",
      comment: "Maravilhoso! Adorei os bombons.",
      avatar: "L",
    },
    {
      id: 10,
      author: "Rogério N.",
      rating: 5,
      date: "29/01/2026",
      comment: "Chocolate delicioso! Recomendo muito.",
      avatar: "R",
    },
    {
      id: 11,
      author: "Sueli C.",
      rating: 4.5,
      date: "27/01/2026",
      comment: "Produto excelente! Vale cada centavo.",
      avatar: "S",
    },
  ],
  11: [
    {
      id: 1,
      author: "Talita M.",
      rating: 5,
      date: "18/02/2026",
      comment: "Dreams é sensacional! O merengue de morango é divino.",
      avatar: "T",
    },
    {
      id: 2,
      author: "Renan S.",
      rating: 5,
      date: "15/02/2026",
      comment: "Sabor incrível! Diferenciado e de alta qualidade.",
      avatar: "R",
    },
    {
      id: 3,
      author: "Karina P.",
      rating: 4.5,
      date: "12/02/2026",
      comment: "Adorei a combinação! Chocolate e morango perfeitos.",
      avatar: "K",
    },
    {
      id: 4,
      author: "Guilherme F.",
      rating: 5,
      date: "10/02/2026",
      comment: "Produto excelente! Minha esposa amou.",
      avatar: "G",
    },
    {
      id: 5,
      author: "Mônica L.",
      rating: 5,
      date: "07/02/2026",
      comment: "Delicioso! O merengue é muito gostoso.",
      avatar: "M",
    },
    {
      id: 6,
      author: "César R.",
      rating: 4.5,
      date: "05/02/2026",
      comment: "Muito bom! Qualidade impecável.",
      avatar: "C",
    },
    {
      id: 7,
      author: "Eduarda T.",
      rating: 5,
      date: "03/02/2026",
      comment: "Perfeito! Super recomendo.",
      avatar: "E",
    },
    {
      id: 8,
      author: "Nelson B.",
      rating: 5,
      date: "01/02/2026",
      comment: "Excelente produto! Vale muito a pena.",
      avatar: "N",
    },
  ],
  12: [
    {
      id: 1,
      author: "Viviane K.",
      rating: 5,
      date: "17/02/2026",
      comment:
        "Zero açúcar e muito gostoso! Perfeito para quem cuida da saúde.",
      avatar: "V",
    },
    {
      id: 2,
      author: "Paulo R.",
      rating: 4.5,
      date: "14/02/2026",
      comment: "Excelente para diabéticos! Sabor muito bom.",
      avatar: "P",
    },
    {
      id: 3,
      author: "Marta S.",
      rating: 5,
      date: "11/02/2026",
      comment: "Adorei! Posso comer sem culpa.",
      avatar: "M",
    },
    {
      id: 4,
      author: "Evandro M.",
      rating: 5,
      date: "09/02/2026",
      comment: "Produto de qualidade! Sabor incrível mesmo sem açúcar.",
      avatar: "E",
    },
    {
      id: 5,
      author: "Sandra F.",
      rating: 4.5,
      date: "06/02/2026",
      comment: "Muito bom! Recomendo para quem tem restrições.",
      avatar: "S",
    },
    {
      id: 6,
      author: "Jorge L.",
      rating: 5,
      date: "04/02/2026",
      comment: "Perfeito! Chocolate delicioso sem açúcar.",
      avatar: "J",
    },
    {
      id: 7,
      author: "Cleusa P.",
      rating: 5,
      date: "02/02/2026",
      comment: "Excelente! Qualidade laCreme sempre surpreende.",
      avatar: "C",
    },
    {
      id: 8,
      author: "Valter N.",
      rating: 4.5,
      date: "31/01/2026",
      comment: "Muito bom! Vale a pena comprar.",
      avatar: "V",
    },
    {
      id: 9,
      author: "Márcia B.",
      rating: 5,
      date: "29/01/2026",
      comment: "Adorei! Produto maravilhoso.",
      avatar: "M",
    },
  ],
  13: [
    {
      id: 1,
      author: "Augusto C.",
      rating: 5,
      date: "16/02/2026",
      comment: "laCreme com bombons é a melhor combinação! Produto excelente.",
      avatar: "A",
    },
    {
      id: 2,
      author: "Sílvia R.",
      rating: 5,
      date: "13/02/2026",
      comment: "Chocolate delicioso! Os bombons são de primeira.",
      avatar: "S",
    },
    {
      id: 3,
      author: "Oswaldo M.",
      rating: 4.5,
      date: "10/02/2026",
      comment: "Muito bom! Qualidade excepcional.",
      avatar: "O",
    },
    {
      id: 4,
      author: "Rosana F.",
      rating: 5,
      date: "08/02/2026",
      comment: "Adorei! laCreme sempre supera as expectativas.",
      avatar: "R",
    },
    {
      id: 5,
      author: "Edilson S.",
      rating: 5,
      date: "05/02/2026",
      comment: "Perfeito! Bombons deliciosos.",
      avatar: "E",
    },
    {
      id: 6,
      author: "Neusa L.",
      rating: 4.5,
      date: "03/02/2026",
      comment: "Excelente produto! Recomendo muito.",
      avatar: "N",
    },
    {
      id: 7,
      author: "Geraldo P.",
      rating: 5,
      date: "01/02/2026",
      comment: "Chocolate premium! Vale cada centavo.",
      avatar: "G",
    },
    {
      id: 8,
      author: "Eliana K.",
      rating: 5,
      date: "30/01/2026",
      comment: "Maravilhoso! Super recomendo.",
      avatar: "E",
    },
    {
      id: 9,
      author: "Waldir B.",
      rating: 4.5,
      date: "28/01/2026",
      comment: "Muito bom! Qualidade impecável.",
      avatar: "W",
    },
    {
      id: 10,
      author: "Ivone G.",
      rating: 5,
      date: "26/01/2026",
      comment: "Produto excelente! Adorei os bombons.",
      avatar: "I",
    },
    {
      id: 11,
      author: "Dorival N.",
      rating: 5,
      date: "24/01/2026",
      comment: "Perfeito! Chocolate de altíssima qualidade.",
      avatar: "D",
    },
    {
      id: 12,
      author: "Célia S.",
      rating: 4.5,
      date: "22/01/2026",
      comment: "Delicioso! Melhor ovo da Páscoa.",
      avatar: "C",
    },
  ],
};

export function getProductReviews(productId: number): Review[] {
  return reviewsData[productId] || [];
}

export function getAverageRating(productId: number): number {
  const reviews = getProductReviews(productId);
  if (reviews.length === 0) return 0;

  const sum = reviews.reduce((acc, review) => acc + review.rating, 0);
  return Number((sum / reviews.length).toFixed(1));
}

export function getReviewCount(productId: number): number {
  return getProductReviews(productId).length;
}
